spring.application.name=Library Management System

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/lms

# Server Configuration
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.security=DEBUG
